### ISSUE TITLE
createCandyGraph() (docs) missing?

### ISSUE THREAD

**Issue by flekschas** [wwwtyro/candygraph#12]
Super uncritical ticket.

The tutorial mentions the `createCandyGraph()` function.

When playing with candyGraph in jsFiddle, I couldn't find that function exposed on the `window.candygraph` object. Then I looked at the [API.md](https://github.com/wwwtyro/candygraph/blob/master/docs/API.md) and couldn't find any mentions of `createCandyGraph()`.

After [searching for it](https://github.com/wwwtyro/candygraph/search?q=createCandyGraph), I wonder if that function was removed at some point? :)

**Comment by wwwtyro** [comment]
Yes, you're 100% correct, that's old. Should be replaced with 

```ts
import { CandyGraph } from "candygraph";

async function main() {
  const cg = new CandyGraph();
  cg.canvas.width = 1024;
  cg.canvas.height = 1024;
}

main();
```
I'll fix it soon if you don't beat me to it. :slightly_smiling_face:

**Comment by flekschas** [comment]
Thanks for fixing the docs :)

**Comment by wwwtyro** [comment]
Oh whoops, I forgot about this. Missed one, too, but just put up a fix. Thanks for the reminder! :sweat_smile:

**Comment by flekschas** [comment]
Oh I thought you fixed it already! Good catch :)
