### ISSUE TITLE
Reduce asset size

### ISSUE THREAD

**Issue by dy** [wwwtyro/candygraph#29]
Just found out this library. I'd imagine perfect graph lib like that.

One question - is that unavoidable to ship Lato font asset? Bundle totals to 100kb gzipped, shaving it off would somewhat reduce size.

There is useful [tiny-sdf](https://github.com/mapbox/tiny-sdf) for that purpose.

**Comment by flekschas** [comment]
The library is tree-shakeable, meaning that only the pieces you import will end up in your final bundle: https://bundlephobia.com/package/candygraph

Also see https://github.com/wwwtyro/candygraph/pull/15.

So if you don't create the default font, it will not impact your bundle size. (All this assume you're using a modern bundler of course)

**Comment by flekschas** [comment]
Tiny-sdf looks cool though! Might be worth seeing how hard it would be to integrate it.

**Comment by dy** [comment]
Enforcing bundler is not friendly, besides it doesn't seem that font is  an edge-case, almost every chart has text.

**Comment by wwwtyro** [comment]
Dang, tiny-sdf does look cool, how have I not seen that before? Agreed, seems worth an experiment. I wonder if there's a tiny-msdf.

**Comment by dy** [comment]
Good call. I suppose msdf would take either converting some msdfgen to wasm or proposing to tiny-sdf a feature. 
Overall one-time font atlas with 256x256 characters is iirc ~30ms, relatively cheap. Plotly uses adaptive atlas generator based on [bitmap-sdf](https://ghub.io/bitmap-sdf), so small sizes are cheap.

**Comment by wwwtyro** [comment]
Nice. I guess plots mostly use small-to-normal text sizes, so maybe sdf is sufficient? Either way, it's what we're using right now, so might as well try this out.

**Comment by wwwtyro** [comment]
I took a swing at this this weekend, but it looks like tiny-sdf doesn't support kerning, unfortunately. I'm going to close this for now, but will remain open to improvements here if and when suitable alternatives are available. Thanks!
