### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by flekschas** [wwwtyro/candygraph#34]
I am using CandyGraph to render a large number of plots per view (50-100) with multiples views. I noticed that every time I switch the view back and forth, the memory footprint of my page goes up and up.

After using the memory profiler of Chrome, I found out that 72% of the memory was retained by `coordinateScopeCache`. It turns out that CandyGraph is caching a Regl `DrawCommand` for every unique coordinate system in `getCoordinateScope`:

```
  private getCoordinateScope(coords: CoordinateSystem) {
    let scope = this.coordinateScopeCache.get(coords);
    if (!scope) {
      scope = coords.scope(this.regl);
      this.coordinateScopeCache.set(coords, scope);
    }
    return scope;
  }
```

https://github.com/wwwtyro/candygraph/blob/master/src/candygraph.ts#L182-L189

Unless I miss something it looks like this cache is never cleared nor is it clearable by a candygraph user. (Something similar seems to be going on for `getCompositeScope()`.)

This seems to be bad for two reasons:
1. Over time, memory _must_ build up because there's no way to clear the cache.
2. It's hard not to slow down the memory build up because coords are created every time a plot is created.

I would propose a function similar to `clearPositionBuffers` that grants access to the internal `coordinateScopeCache` and `compositeScopeCache`. This would allow the user to periodically clear both caches entirely or clear caches upon destruction of a plot (e.g., when I navigate to a new view, I know that I will never re-use the previous coordinate instance again, so I can remove it from the cache)

Actually, why not simply making `coordinateScopeCache` and `compositeScopeCache` public? There's no harm in clearing the cache or is there?

**Update:** I guess similarly, the commandCache is dangerous as it's not clearable.

**Comment by wwwtyro** [comment]
Hey @flekschas, thanks for bringing this up! How would you feel about a more generic `cg.clearCache()` function that just wiped out all the caches? I'm a bit wary about exposing the underlying implementation.

**Comment by flekschas** [comment]
I agree! Exposing the internals is not a good idea. I actually started working on a solution on Friday and seems to work. I'll post more details after the weekend but my idea was to automatically remove cached objects/functions when they are disposed because it seems like there would never be a case where one would run a draw command on disposed resources.

**Comment by flekschas** [comment]
@wwwtyro The scenario where I run into memory issues is related to cases where I am trying to load a lot of plots (e.g., 100) in a small multiple kind of setting. Now I just remembered that previously you implemented this auto-dispose feature and then removed it for simplicity purposes. I am curious, what do you think of re-introducing the auto-disposal option as a feature that has to be turned out explicitly? For scenarios, where one wants to create one-off charts, I think it's a useful feature.

**Comment by wwwtyro** [comment]
That's an interesting idea, I'll definitely give it some thought. Something like a flag on the cg.render() function, perhaps. Off the top of my head, I'm inclined to keep candygraph as simple as possible to serve as a low level layer, with features like this handled at a higher level (along with things like handling devicePixelRatio).

**Comment by wwwtyro** [comment]
I've been thinking about this a bit. I _think_ that any untracked primitives and datasets should be automatically garbage collected (ignoring for now any associated draw commands that may be cached). If this is the case, then I assume we should be okay without a flag. Can you let me know if you're seeing memory issues that contradict my assumption? If so, we should revisit this. Thanks again!

**Comment by flekschas** [comment]
Just for context, when I was thinking of an optional _auto-disposal_ feature I was more thinking of cases where the application component is retained and might occasionally be updated. (E.g., in a small multiples/trellis plot kind of situation). Hence, references are still in place and normal garbage collection would not kick in my understanding. I can of course, manually dispose everything after `cg.render(...)` but it would be cool if something like `cg.render(..., { autoDispose: true})` would take of it as was previously the case.

**Comment by wwwtyro** [comment]
I think what is tripping me up is that I'm having trouble imagining a situation in which references to known-disposed (because `autoDispose: true` was used) primitives would be kept. They can't be used once disposed, so would the user still want a reference to them? I'm probably missing something, thanks for any clarification.

**Comment by flekschas** [comment]
> Can you let me know if you're seeing memory issues that contradict my assumption?

@wwwtyro Sorry it took me so long to test the garbage collection. I can confirm I am not seeing a memory leak, so you're right, a feature like `autoDispose: true`, might not be necessary.

> They can't be used once disposed, so would the user still want a reference to them? I'm probably missing something, thanks for any clarification.

Just FYI, I ran into this issue when using CandyGraph within React where I was referencing resources beyond the rendering via React hooks, which likely caused the memory leak. In that case I thought `autoDispose: true` could be handy option but it's easier to just refactor the render function actually.

**Comment by wwwtyro** [comment]
No worries at all, thank you!

**Comment by shamrin** [comment]
@wwwtyro:
> I _think_ that any untracked primitives and datasets should be automatically garbage collected (ignoring for now any associated draw commands that may be cached). ... Can you let me know if you're seeing memory issues that contradict my assumption?

Indeed we found a contradiction. As @wwwtyro mentioned, JS GC probably doesn't kick in fast enough to prevent GPU memory leaks during animation: https://github.com/wwwtyro/candygraph/issues/38#issuecomment-1175602748

I don't know if auto-disposal feature should be restored or not. But the following is needed:

1.  Some straightforward manual way to `.dispose()` unneeded objects. Solving #40 should help.
2. Some way to reuse unchanged objects. For example, I don't know how to skip re-creating Axis that don't change throughout the animation. See my [sidenote about the yaxis in the tutorial](https://github.com/wwwtyro/candygraph/pull/39/files#r915633970).

I think number 1 is important to make leaks hard to introduce. Number 2 is good to have, but not critical.

**Comment by wwwtyro** [comment]
Thanks @shamrin and @flekschas, I should have time to dig into this over the weekend.

**Comment by wwwtyro** [comment]
@shamrin I had a moment to take a look at this this evening. I had forgotten, but since `Scissor` extends the `Composite` class, it already has a `dispose` function. I just tested it out, and it keeps the GPU memory in check.

I think your point number 2 above should be addressed by simply keeping a reference to the y-axis and reusing it in the call to render. I think I'll update the example to demonstrate this.

**Comment by shamrin** [comment]
@wwwtyro Thank you! Indeed, I forgot to check the parent class of `Scissor`.

Good idea on keeping the y-axis!

**Comment by wwwtyro** [comment]
I think I'm going to close this issue. My take here is that our command memory use is limited by the various combinations of primitives and coordinate systems, the maximum of which is not onerous to my eye. I think it's safe to view the various caches here as storing lazily-initialized objects; they are not unbounded. Between that perspective and the discussion around GC, I think I'm satisfied with the status quo. Feel free to reopen if anyone thinks I'm missing something!
