### ISSUE TITLE
Make alpha true or configurable? 

### ISSUE THREAD

**Issue by jpambrun** [wwwtyro/candygraph#8]
The clearing alpha value (e.g. `cg.clear([1, 1, 1, 0.5]);`) has no effect. It seems related to alpha being disable at the REGL level [here](https://github.com/wwwtyro/candygraph/blob/b6d4e9e9e15fe640e83013aab793b93f71eef681/src/candygraph.ts#L68).

I am trying to paint over existing html content.

**Comment by wwwtyro** [comment]
Thanks, I'll look into fixing this :+1:

**Comment by wwwtyro** [comment]
I've added an option to make the canvas `alpha` attribute configurable in the `CandyGraph` constructor; check out the API docs. :slightly_smiling_face::+1:
